<div3 id="Mar" class="col-sm-6">
<h style="font-size:36px;">Mar</h>
  Marquasia Hayes is a rising sophomore in her school Rochester Prep High. Born December 18 to a family of feminists she was always outspoken and a wonderful debater. She always was a feminist, although she didn’t initially identify as one due to the stigma around the name “feminist”. As she grew and began doing real research into the real definition of a feminist, she began to identify as one, much to the chagrin of many miseducators on femininity and the mindset of a true feminist. She has four younger sisters so she needed to be able to teach them how to be a feminist and the men that they will encounter may or may not be feminist but that doesn’t define them. It seemed only right to take a coding course being that her favorite subject is math, and whilst in the course she garnered the skills required to create the website that defined her feelings wholeheartedly. She collaborated with Leah Moore on Guerrilla Feminist because she doesn’t want impressionable young women and men to get the wrong ideas about how to be a feminist and buy into the hype surrounding it. Her favorite hobbies include reading, cooking, and chipping the glass ceiling with her fellow strong women.


  <div2 id="Leah" class="col-sm-6">
      <h style="font-size:36px;">Leah</h>
At the young age of fourteen, Leah Grace is an unstoppable female. When she was thirteen years old she had a contorting ovarian cyst and needed surgery to remove it. She had been told time and time again that she mustn't bring her pain up in conversation because it is “something that is not polite to talk about”, but being silenced did not stop her. She had been silenced on talking about her experiences with sexual harassment and an eating disorder. She believes in breaking the silence and helping other women do the same. Being silenced about standing for feminism was something she had experienced ever since fifth grade, and many other girls to this day as well. These experiences all encouraged her to stand for and help other women to break the silence surrounding current issues and to stand for feminism. The stigma surrounding the title “feminist” is something she has been working to stop with her partner, Marquasia. As well as the stigma surrounding being victimized, she believes in enforcing that past experiences do not make the victim “weak” or “dumb”. She believes that if anything, it makes them stronger. These are all the reasons that she collaborated with Marquasia Hayes in creating the website and brand, Guerilla Feminist. She thanks you for reading this and checking out her and Marquasia’s website, and she thanks you for helping to change our world and for believing in equality.
  </div>
<span </span>
